# JWT 설정
jwt:
  issuer: "FestivalDotCom"  # JWT 발행자 이름
  secret-key: ${JWT_SECRET_KEY}
  expiry-seconds:
    access-token: 1800  # 액세스 토큰의 만료 시간 (초 단위)
    refresh-token: 36000 # 리프레시 토큰의 만료 시간 (초 단위), 설정을 생략할 경우 36000이 기본값으로 사용됨 604800

# OAuth 2.0 설정
spring:
  config:
#    import: optional:file:.env[.properties]
    import: optional:file:.env[.yml]

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${APP_BASEURL}
            scope: profile
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${APP_BASEURL}
            scope: name,email,profile_image
            authorization-grant-type: authorization_code
            client-name: Naver
            client-authentication-method: client_secret_post
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${APP_BASEURL}
            scope: profile_nickname, profile_image
#            scope: profile_nickname, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id